### ISSUE TITLE
Upgrade to dotnet 6.0

### ISSUE THREAD

**Issue by nakamura2000** [flakey-bit/DotNetDigestAuth#22]
Upgrade to dotnet core 6.0 because current release is based on asp.net core 2.0.

**Comment by flakey-bit** [comment]
Hi,

@nakamura2000 

I've pushed some changes (https://github.com/flakey-bit/DotNetDigestAuth/commit/68402cc816d4eaaaaaa3559f59ed5facde3de46a) which should hopefully address this for you - new package here: 
https://www.nuget.org/packages/FlakeyBit.DigestAuthentication.AspNetCore/2023.7.16.5

Let me know if I missed something else from your PR (https://github.com/flakey-bit/DotNetDigestAuth/pull/23) otherwise I'll close it. 


Cheers,
Eddie

**Comment by nakamura2000** [comment]
Thank you! I think it's no missing.
