### ISSUE TITLE
Using FlakeyBit.DigestAuthentication.AspNetCore 2019.3.20.3 generates package warnings

### ISSUE THREAD

**Issue by jimevans** [flakey-bit/DotNetDigestAuth#3]
The ASP.NET Core NuGet package has a stated dependency on the FlakeyBit.DigestAuthentication.Implementation NuGet package with a version greater than or equal to 2019.3.20.3. Since there is no .3 package, only .4, this causes a warning when restoring packages using Visual Studio 2019.

This is understandably just a nuisance issue, so if you'd want to simply close it without taking any action on it, that's understandable. Otherwise, publishing a new ASP.NET Core package with the bumped implementation package dependency should clear up the issue.

**Comment by flakey-bit** [comment]
This should be fixed by cda1841e4d47eb9a466c47b4496f0906dbe6cad1 - see new builds:

- [FlakeyBit.DigestAuthentication.AspNetCore: 2019.5.25.1](https://www.nuget.org/packages/FlakeyBit.DigestAuthentication.AspNetCore/2019.5.25.1)

- [FlakeyBit.DigestAuthentication.AspNetClassic: 2019.5.25.1](https://www.nuget.org/packages/FlakeyBit.DigestAuthentication.AspNetClassic/2019.5.25.1)

I've also unlisted `FlakeyBit.DigestAuthentication.Implementation` from the NuGet search results.
